"""empty message

Revision ID: a3f7f4549048
Revises: 
Create Date: 2022-10-31 10:21:04.450202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3f7f4549048'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boleto',
    sa.Column('idBoleto', sa.Integer(), nullable=False),
    sa.Column('funcion', sa.String(length=250), nullable=True),
    sa.Column('fechaFuncion', sa.String(length=250), nullable=True),
    sa.Column('precio', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('idBoleto')
    )
    op.create_table('cine',
    sa.Column('idCine', sa.Integer(), nullable=False),
    sa.Column('nombreCine', sa.String(length=250), nullable=True),
    sa.Column('direccion', sa.String(length=250), nullable=True),
    sa.Column('numSalas', sa.Integer(), nullable=True),
    sa.Column('horario', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('idCine')
    )
    op.create_table('pelicula',
    sa.Column('idPelicula', sa.Integer(), nullable=False),
    sa.Column('nombrePelicula', sa.String(length=250), nullable=True),
    sa.Column('fechaEstreno', sa.String(length=250), nullable=True),
    sa.Column('estudioCinematografico', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('idPelicula')
    )
    op.create_table('producto',
    sa.Column('idProducto', sa.Integer(), nullable=False),
    sa.Column('nombreProducto', sa.String(length=250), nullable=True),
    sa.Column('inventario', sa.Integer(), nullable=True),
    sa.Column('precioVenta', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('idProducto')
    )
    op.create_table('sala_cine',
    sa.Column('idSala', sa.Integer(), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=True),
    sa.Column('ocupado', sa.String(length=250), nullable=True),
    sa.Column('horaProxFuncion', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('idSala')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sala_cine')
    op.drop_table('producto')
    op.drop_table('pelicula')
    op.drop_table('cine')
    op.drop_table('boleto')
    # ### end Alembic commands ###
