# Generated by Django 4.1.2 on 2022-10-31 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_cla', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_pla', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=30)),
                ('capitulos', models.CharField(max_length=5)),
                ('calificacion', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=30)),
                ('calificacion', models.CharField(max_length=3)),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorapp.plataforma')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=50)),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorapp.clasificacion')),
            ],
        ),
    ]
